import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MenuBar from "./components/MenuBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Time management",
  description: "Generated by create next app",
};

import Header from "./components/Header";
import PageLayout from "./components/PageLayout";
import ThemeProvider from "./components/ThemeProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} 
        ${geistMono.variable} 
        antialiased font-sans bg-background text-foreground min-h-screen flex flex-col`}
        style={{ colorScheme: 'light dark' }}
        suppressHydrationWarning
      >
        <ThemeProvider>
          <Header />
          <PageLayout>{children}</PageLayout>
          <MenuBar />
        </ThemeProvider>
      </body>
    </html>
  );
}
